export const SHOW_SNACKBAR_EVENT = "SHOW_SNACKBAR";
export const SHOW_NEW_VERSION_EVENT = "SHOW_NEW_VERSION_EVENT";
export const CLOSE_DRAWER_EVENT = "CLOSE_DRAWER_EVENT";
export const OPEN_BOTTOM_DRAWER_EVENT = "OPEN_BOTTOM_DRAWER_EVENT";