export const SHOW_SNACKBAR_EVENT = "SHOW_SNACKBAR";
export const SHOW_NEW_VERSION_EVENT = "SHOW_NEW_VERSION_EVENT";
export const CLOSE_DRAWER_EVENT = "CLOSE_DRAWER_EVENT";
export const OPEN_BOTTOM_DRAWER_EVENT = "OPEN_BOTTOM_DRAWER_EVENT";
export const START_PROGRESS_EVENT = "START_PROGRESS_EVENT";
export const STOP_PROGRESS_EVENT = "STOP_PROGRESS_EVENT";
export const CANVAS_PINCH_EVENT = "CANVAS_PINCH_EVENT";
export const CANVAS_MOVE_EVENT = "CANVAS_MOVE_EVENT";